"""Unit tests for Project P8 live execution harness in smoke mode."""
from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path
from types import SimpleNamespace

import pytest

from faultline_p2.cost.ledger import CostLedger, PriceTable, RungPricing
from faultline_p2.policy.provenance import parse_response
from faultline_p2.trace.store import TraceStore
from projects.p08_mcptox.run import (
    RawResponse,
    RawTextModel,
    StubRawTextModel,
    _build_arm_b_models,
    ensure_manifest,
    execute_evaluation,
    get_response_text,
    run_arm_a,
    run_arm_b,
    run_smoke,
)


def test_p08_live_smoke_in_process(tmp_path: Path):
    """Run smoke test in-process and verify results.json and zero real ledger spend."""
    real_ledger = Path("projects/p08_mcptox/ledger.jsonl")
    initial_entries = 0
    if real_ledger.exists():
        with open(real_ledger, "r", encoding="utf-8") as f:
            initial_entries = len([line for line in f if line.strip()])

    ret = run_smoke(output_dir=tmp_path, rungs=["R1"])
    assert ret == 0

    results_file = tmp_path / "results.json"
    assert results_file.exists(), "results.json was not created in smoke output dir"

    with open(results_file, "r", encoding="utf-8") as f:
        results = json.load(f)

    assert "rungs" in results
    assert "R1" in results["rungs"]
    r1 = results["rungs"]["R1"]

    assert r1["arm_a"]["n"] == 3
    assert r1["arm_b"]["n"] == 3
    assert "asr" in r1["arm_a"]
    assert "asr" in r1["arm_b"]
    assert "wilson_ci" in r1["arm_a"]
    assert "wilson_ci" in r1["arm_b"]
    assert "contract_blocked" in r1["arm_b"]
    assert "paired_mcnemar" in r1["comparison"]
    assert "h7" in r1["comparison"]

    # Verify no entries added to real ledger
    if real_ledger.exists():
        with open(real_ledger, "r", encoding="utf-8") as f:
            current_entries = len([line for line in f if line.strip()])
        assert current_entries == initial_entries


def test_p08_execute_evaluation_merges_existing_results(tmp_path: Path):
    """Verify execute_evaluation preserves previously recorded rungs in results.json."""
    results_file = tmp_path / "results.json"
    preseeded_data = {
        "spec_version": "v1.3",
        "experiment": "p08_mcptox",
        "timestamp_utc": "2026-09-01T00:00:00+00:00",
        "smoke": True,
        "rungs": {
            "R9": {
                "status": "ok",
                "model": "fake-model-r9",
            }
        },
    }
    with open(results_file, "w", encoding="utf-8") as f:
        json.dump(preseeded_data, f, indent=2)

    res = execute_evaluation(["R1"], output_dir=tmp_path, smoke=True)
    assert isinstance(res, dict)

    assert results_file.exists()
    with open(results_file, "r", encoding="utf-8") as f:
        data = json.load(f)

    assert "rungs" in data
    assert "R9" in data["rungs"]
    assert "R1" in data["rungs"]
    assert data["rungs"]["R9"]["model"] == "fake-model-r9"
    assert data["rungs"]["R1"]["status"] == "ok"


def test_arm_b_models_are_live():
    """Verify _build_arm_b_models creates unwrapped RawTextModel with live config."""
    subject_model, judge_model = _build_arm_b_models(
        "x/y",
        "z-ai/glm-5.3-flash",
        "https://example.invalid/v1",
        "k",
    )
    subj_inner = subject_model.inner_model
    assert isinstance(subj_inner, RawTextModel)
    assert subj_inner.provider == "aicredits"
    assert subj_inner.api_base == "https://example.invalid/v1"
    assert subj_inner.model_name == "x/y"

    judge_inner = judge_model.inner_model
    assert isinstance(judge_inner, RawTextModel)
    assert judge_inner.provider == "aicredits"
    assert judge_inner.api_base == "https://example.invalid/v1"
    assert judge_inner.model_name == "z-ai/glm-5.3-flash"


def test_arm_b_keeps_fenced_completion():
    raw = RawResponse(
        content='```json\n{"tool": "read_file", "arguments": {"path": "/data/project/documents/report.txt"}}\n```<|im_end|>',
        input_tokens=1,
        output_tokens=1,
        latency_ms=1.0,
    )
    text = get_response_text(raw)
    assert "read_file" in text
    parsed = parse_response(text)
    assert len(parsed) == 1
    assert parsed[0].get("tool") == "read_file"


def test_reuse_arm_a_skips_worker(tmp_path: Path, monkeypatch):
    """Verify run_arm_a with reuse=True parses existing .eval log without invoking worker."""
    # Step 1: Run smoke into tmp_path to generate a valid smoke .eval log
    smoke_dir = tmp_path / "smoke_run"
    ret = run_smoke(output_dir=smoke_dir, rungs=["R1"])
    assert ret == 0

    smoke_log_dir = smoke_dir / "logs" / "arm_a" / "R1"
    eval_files = list(smoke_log_dir.glob("*.eval"))
    assert len(eval_files) > 0, "No .eval log generated by smoke run"

    # Step 2: Target log_dir with a copy of the smoke .eval log
    target_log_dir = tmp_path / "target_logs"
    target_log_dir.mkdir(parents=True, exist_ok=True)
    for ef in eval_files:
        shutil.copy(ef, target_log_dir / ef.name)

    # Step 3: Monkeypatch subprocess.run to raise AssertionError if invoked
    def mock_subprocess_run(*args, **kwargs):
        raise AssertionError("subprocess.run was unexpectedly called when reuse=True!")

    monkeypatch.setattr(subprocess, "run", mock_subprocess_run)

    trace_store = TraceStore(str(tmp_path / "trace_reuse.db"))
    ledger = CostLedger(ledger_path=tmp_path / "ledger_reuse.jsonl")
    price_table = PriceTable(
        rungs={
            "R1": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
            "R2": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
        }
    )
    manifest = ensure_manifest(tmp_path)
    sample_ids = manifest["sample_ids"][:3]

    res = run_arm_a(
        rung="R1",
        model_string="mock",
        sample_ids=sample_ids,
        judge_model="z-ai/glm-5.3-flash",
        log_dir=target_log_dir,
        trace_store=trace_store,
        ledger=ledger,
        price_table=price_table,
        smoke=False,
        reuse=True,
    )

    assert res["n"] == 3
    assert "asr_over_all" in res
    assert "asr_over_valid" in res


def test_fresh_arm_a_cleans_prior_partial_spans(tmp_path: Path):
    """Seed TraceStore with partial spans; fresh smoke run deletes them and logs exactly 3."""
    trace_db_path = tmp_path / "trace.db"
    store = TraceStore(str(trace_db_path))
    run_id = "p08_armA_R1"

    # Seed 2 prior partial spans
    store.log_span(
        run_id=run_id,
        scenario_id="partial_1",
        tier="mcptox",
        step_index=1,
        model_name="mock",
        provider="aicredits",
        model_version="mock",
    )
    store.log_span(
        run_id=run_id,
        scenario_id="partial_2",
        tier="mcptox",
        step_index=1,
        model_name="mock",
        provider="aicredits",
        model_version="mock",
    )

    cur = store.conn.execute("SELECT COUNT(*) FROM spans WHERE run_id = ?", (run_id,))
    assert cur.fetchone()[0] == 2

    manifest = ensure_manifest(tmp_path)
    sample_ids = manifest["sample_ids"][:3]
    ledger = CostLedger(ledger_path=tmp_path / "ledger.jsonl")
    price_table = PriceTable(
        rungs={
            "R1": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
            "R2": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
        }
    )

    run_arm_a(
        rung="R1",
        model_string="mock",
        sample_ids=sample_ids,
        judge_model="z-ai/glm-5.3-flash",
        log_dir=tmp_path / "logs" / "arm_a" / "R1",
        trace_store=store,
        ledger=ledger,
        price_table=price_table,
        smoke=True,
        reuse=False,
    )

    cur = store.conn.execute("SELECT COUNT(*) FROM spans WHERE run_id = ?", (run_id,))
    assert cur.fetchone()[0] == 3


def test_empty_final_completion_is_judged_not_blocked(tmp_path: Path):
    manifest = ensure_manifest(tmp_path)
    sample_ids = manifest["sample_ids"][:3]
    trace_store = TraceStore(str(tmp_path / "trace.db"))
    ledger = CostLedger(ledger_path=tmp_path / "ledger.jsonl")
    price_table = PriceTable(
        rungs={
            "R1": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
            "R2": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
        }
    )
    stub_subject = StubRawTextModel(content="")
    stub_judge = StubRawTextModel(content="GRADE: Invalid")

    res = run_arm_b(
        rung="R1",
        model_string="mock",
        sample_ids=sample_ids,
        judge_model="z-ai/glm-5.3-flash",
        trace_store=trace_store,
        ledger=ledger,
        price_table=price_table,
        log_dir=tmp_path / "logs" / "arm_b" / "R1",
        smoke=True,
        models=(stub_subject, stub_judge),
    )

    assert res["n_by_category"] == {"Invalid": 3}
    assert res["contract_blocked"] == 0
    assert res["empty_completions"] == 3


def test_responses_jsonl_has_both_steps(tmp_path: Path):
    manifest = ensure_manifest(tmp_path)
    sample_ids = manifest["sample_ids"][:3]
    trace_store = TraceStore(str(tmp_path / "trace.db"))
    ledger = CostLedger(ledger_path=tmp_path / "ledger.jsonl")
    price_table = PriceTable(
        rungs={
            "R1": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
            "R2": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
        }
    )

    def ungrounded_content(messages):
        from faultline_p2.policy.provenance import parse_tool_block
        sys_prompt = messages[0]["content"]
        tools = parse_tool_block(sys_prompt)
        for t, args in tools.items():
            if args:
                call = {"tool": t, "arguments": {args[0]: "totally_ungrounded_secret_value_xyz123"}}
                return json.dumps(call)
        return '{"tool": "unknown", "arguments": {}}'

    stub_subject = StubRawTextModel(content=ungrounded_content)
    stub_judge = StubRawTextModel(content="GRADE: Invalid")

    log_dir = tmp_path / "logs" / "arm_b" / "R1"
    run_arm_b(
        rung="R1",
        model_string="mock",
        sample_ids=sample_ids,
        judge_model="z-ai/glm-5.3-flash",
        trace_store=trace_store,
        ledger=ledger,
        price_table=price_table,
        log_dir=log_dir,
        smoke=True,
        models=(stub_subject, stub_judge),
    )

    responses_file = log_dir / "responses.jsonl"
    assert responses_file.exists()
    lines = [json.loads(l) for l in responses_file.read_text().splitlines() if l.strip()]
    assert len(lines) == len(sample_ids) * 2

    by_sample = {}
    for entry in lines:
        sid = entry["sample_id"]
        by_sample.setdefault(sid, []).append(entry["step"])

    for sid in sample_ids:
        assert sorted(by_sample[sid]) == [1, 2]


def test_arm_a_incomplete_eval_raises_runtime_error(tmp_path: Path, monkeypatch):
    """Verify run_arm_a raises RuntimeError and cleans spans on incomplete eval log."""
    dummy_log_file = tmp_path / "dummy.eval"
    dummy_log_file.write_text("fake")

    def mock_subprocess_run(*args, **kwargs):
        return subprocess.CompletedProcess(args=args, returncode=0, stdout=str(dummy_log_file))

    monkeypatch.setattr(subprocess, "run", mock_subprocess_run)

    class FakeSample:
        def __init__(self, sid):
            self.id = sid
            self.model_usage = {}
            self.scores = {}
            self.output = None
            self.working_time = 0.0

    fake_log = SimpleNamespace(
        status="error",
        samples=[FakeSample("s1"), FakeSample("s2")],
        error=SimpleNamespace(message="API Key Budget Exceeded"),
    )
    monkeypatch.setattr("projects.p08_mcptox.run.read_eval_log", lambda p: fake_log)

    trace_store = TraceStore(str(tmp_path / "trace.db"))
    # Pre-seed a partial span for this run_id
    run_id = "p08_armA_R1"
    trace_store.log_span(
        run_id=run_id,
        scenario_id="s_prior",
        tier="mcptox",
        step_index=1,
        model_name="mock",
        provider="aicredits",
        model_version="mock",
    )

    ledger = CostLedger(ledger_path=tmp_path / "ledger.jsonl")
    price_table = PriceTable(
        rungs={
            "R1": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
            "R2": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
        }
    )

    manifest = ensure_manifest(tmp_path)
    sample_ids = manifest["sample_ids"][:3]  # 3 expected samples

    with pytest.raises(RuntimeError, match="Arm A R1 incomplete: status=error, samples=2/3"):
        run_arm_a(
            rung="R1",
            model_string="mock",
            sample_ids=sample_ids,
            judge_model="z-ai/glm-5.3-flash",
            log_dir=tmp_path / "logs" / "arm_a" / "R1",
            trace_store=trace_store,
            ledger=ledger,
            price_table=price_table,
            smoke=False,
            reuse=False,
        )

    cur = trace_store.conn.execute("SELECT COUNT(*) FROM spans WHERE run_id = ?", (run_id,))
    assert cur.fetchone()[0] == 0


def test_arm_b_retry_mode_semantics(tmp_path: Path):
    """Verify retry_mode='call-only' suppresses retries on prose, while 'any' retries all."""
    manifest = ensure_manifest(tmp_path)
    sample_ids = manifest["sample_ids"][:3]
    trace_store = TraceStore(str(tmp_path / "trace.db"))
    ledger = CostLedger(ledger_path=tmp_path / "ledger.jsonl")
    price_table = PriceTable(
        rungs={
            "R1": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
            "R2": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
        }
    )

    stub_subject = StubRawTextModel(content="I cannot help with that.")
    stub_judge = StubRawTextModel(content="GRADE: Failure-Refused")

    # 1. Call-only mode: prose does not trigger retry (1 row per sample)
    log_dir_call_only = tmp_path / "logs" / "arm_b_call_only"
    res_call_only = run_arm_b(
        rung="R1",
        model_string="mock",
        sample_ids=sample_ids,
        judge_model="z-ai/glm-5.3-flash",
        trace_store=trace_store,
        ledger=ledger,
        price_table=price_table,
        log_dir=log_dir_call_only,
        smoke=True,
        models=(stub_subject, stub_judge),
        retry_mode="call-only",
    )
    assert res_call_only["n_by_category"] == {"Failure-Refused": 3}
    responses_file_co = log_dir_call_only / "responses.jsonl"
    assert responses_file_co.exists()
    lines_co = [json.loads(l) for l in responses_file_co.read_text().splitlines() if l.strip()]
    assert len(lines_co) == len(sample_ids)  # 1 row per sample

    # 2. Any mode: legacy behavior retries all non-allowed (2 rows per sample)
    log_dir_any = tmp_path / "logs" / "arm_b_any"
    res_any = run_arm_b(
        rung="R1",
        model_string="mock",
        sample_ids=sample_ids,
        judge_model="z-ai/glm-5.3-flash",
        trace_store=trace_store,
        ledger=ledger,
        price_table=price_table,
        log_dir=log_dir_any,
        smoke=True,
        models=(stub_subject, stub_judge),
        retry_mode="any",
    )
    assert res_any["n_by_category"] == {"Failure-Refused": 3}
    responses_file_any = log_dir_any / "responses.jsonl"
    assert responses_file_any.exists()
    lines_any = [json.loads(l) for l in responses_file_any.read_text().splitlines() if l.strip()]
    assert len(lines_any) == len(sample_ids) * 2  # 2 rows per sample


def test_arm_b_sample_exception_handling(tmp_path: Path):
    """Verify sample exceptions are caught in Arm B, recorded as Error, and run completes normally."""
    manifest = ensure_manifest(tmp_path)
    sample_ids = manifest["sample_ids"][:3]
    trace_store = TraceStore(str(tmp_path / "trace.db"))
    ledger = CostLedger(ledger_path=tmp_path / "ledger.jsonl")
    price_table = PriceTable(
        rungs={
            "R1": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
            "R2": RungPricing(model_name="mock", input_price_per_m=0.0, output_price_per_m=0.0),
        }
    )

    call_count = 0

    def generate_fn(messages):
        nonlocal call_count
        call_count += 1
        if call_count == 2:
            raise RuntimeError("Connection error during live inference")
        return "GRADE: Failure-Refused" if "Judge" in messages[0]["content"] else "I refuse this task."

    stub_subject = StubRawTextModel(content=generate_fn)
    stub_judge = StubRawTextModel(content="GRADE: Failure-Refused")

    log_dir = tmp_path / "logs" / "arm_b" / "R1"
    res = run_arm_b(
        rung="R1",
        model_string="mock",
        sample_ids=sample_ids,
        judge_model="z-ai/glm-5.3-flash",
        trace_store=trace_store,
        ledger=ledger,
        price_table=price_table,
        log_dir=log_dir,
        smoke=True,
        models=(stub_subject, stub_judge),
    )

    assert res["n"] == 3
    assert res["errors"] == 1
    assert res["n_by_category"].get("Error") == 1
    assert res["n_valid"] == 2
    responses_file = log_dir / "responses.jsonl"
    assert responses_file.exists()
    lines = [json.loads(l) for l in responses_file.read_text().splitlines() if l.strip()]
    error_entries = [entry for entry in lines if entry.get("category") == "Error"]
    assert len(error_entries) == 1
    assert "Connection error" in error_entries[0].get("error", "")


