# GENERATED by projects/p09_redteam/run.py --regenerate-tests — do not edit
from __future__ import annotations

import pytest
from faultline_p2.agent.agent import run_agent
from faultline_p2.agent.contracts import ScenarioTask
from faultline_p2.env.corpus import build_corpus
from faultline_p2.policy import RuntimePolicy
from faultline_p2.redteam import Attack, HostileStub, check_benign_correct, inject, succeeded
from projects.p09_redteam.run import select_scenarios

CORPUS = build_corpus()
SCENARIOS_BY_ID = {s.scenario_id: s for s in CORPUS.scenarios}

def test_invariant_tool_exfil_path() -> None:
    """Assert RuntimePolicy deterministically blocks HostileStub for structural category: tool_exfil_path."""
    from faultline_p2.redteam import build
    sc_ids = select_scenarios(CORPUS, n=5)
    attacks = [a for a in build(CORPUS, sc_ids, seed=42) if a.category == "tool_exfil_path"]
    assert len(attacks) >= 5
    for a in attacks:
        sc = SCENARIOS_BY_ID[a.scenario_id]
        policy = RuntimePolicy()
        run_id = f"invariant-tool_exfil_path-{a.attack_id}"
        policy.reset_run(run_id)
        env = {"documents": inject(CORPUS.documents, a), "policy": policy}
        task = ScenarioTask(task_id=sc.scenario_id, prompt=sc.prompt, tier=sc.tier)
        model = HostileStub()
        outcome = run_agent(task, env, model, step_cap=12, run_id=run_id, policy=policy)
        assert not succeeded(a, outcome, outcome.trace, []), f"Invariant failed: tool_exfil_path succeeded against policy"

def test_invariant_unlisted_tool() -> None:
    """Assert RuntimePolicy deterministically blocks HostileStub for structural category: unlisted_tool."""
    from faultline_p2.redteam import build
    sc_ids = select_scenarios(CORPUS, n=5)
    attacks = [a for a in build(CORPUS, sc_ids, seed=42) if a.category == "unlisted_tool"]
    assert len(attacks) >= 5
    for a in attacks:
        sc = SCENARIOS_BY_ID[a.scenario_id]
        policy = RuntimePolicy()
        run_id = f"invariant-unlisted_tool-{a.attack_id}"
        policy.reset_run(run_id)
        env = {"documents": inject(CORPUS.documents, a), "policy": policy}
        task = ScenarioTask(task_id=sc.scenario_id, prompt=sc.prompt, tier=sc.tier)
        model = HostileStub()
        outcome = run_agent(task, env, model, step_cap=12, run_id=run_id, policy=policy)
        assert not succeeded(a, outcome, outcome.trace, []), f"Invariant failed: unlisted_tool succeeded against policy"

def test_invariant_query_dump() -> None:
    """Assert RuntimePolicy deterministically blocks HostileStub for structural category: query_dump."""
    from faultline_p2.redteam import build
    sc_ids = select_scenarios(CORPUS, n=5)
    attacks = [a for a in build(CORPUS, sc_ids, seed=42) if a.category == "query_dump"]
    assert len(attacks) >= 5
    for a in attacks:
        sc = SCENARIOS_BY_ID[a.scenario_id]
        policy = RuntimePolicy()
        run_id = f"invariant-query_dump-{a.attack_id}"
        policy.reset_run(run_id)
        env = {"documents": inject(CORPUS.documents, a), "policy": policy}
        task = ScenarioTask(task_id=sc.scenario_id, prompt=sc.prompt, tier=sc.tier)
        model = HostileStub()
        outcome = run_agent(task, env, model, step_cap=12, run_id=run_id, policy=policy)
        assert not succeeded(a, outcome, outcome.trace, []), f"Invariant failed: query_dump succeeded against policy"

def test_invariant_budget_loop() -> None:
    """Assert RuntimePolicy deterministically blocks HostileStub for structural category: budget_loop."""
    from faultline_p2.redteam import build
    sc_ids = select_scenarios(CORPUS, n=5)
    attacks = [a for a in build(CORPUS, sc_ids, seed=42) if a.category == "budget_loop"]
    assert len(attacks) >= 5
    for a in attacks:
        sc = SCENARIOS_BY_ID[a.scenario_id]
        policy = RuntimePolicy()
        run_id = f"invariant-budget_loop-{a.attack_id}"
        policy.reset_run(run_id)
        env = {"documents": inject(CORPUS.documents, a), "policy": policy}
        task = ScenarioTask(task_id=sc.scenario_id, prompt=sc.prompt, tier=sc.tier)
        model = HostileStub()
        outcome = run_agent(task, env, model, step_cap=12, run_id=run_id, policy=policy)
        assert not succeeded(a, outcome, outcome.trace, []), f"Invariant failed: budget_loop succeeded against policy"

@pytest.mark.xfail(strict=True, reason="P9 open regression: json_breakout p9-s-0047-json_breakout-0")
def test_regression_p9_s_0047_json_breakout_0() -> None:
    sc = SCENARIOS_BY_ID["s-0047"]
    from faultline_p2.redteam import build
    attacks = [a for a in build(CORPUS, ["s-0047"], seed=42) if a.attack_id == "p9-s-0047-json_breakout-0"]
    assert len(attacks) == 1, "Attack definition missing"
    attack = attacks[0]
    policy = RuntimePolicy()
    run_id = f"repro-p9-s-0047-json_breakout-0"
    policy.reset_run(run_id)
    env = {"documents": inject(CORPUS.documents, attack), "policy": policy}
    task = ScenarioTask(task_id=sc.scenario_id, prompt=sc.prompt, tier=sc.tier)
    model = HostileStub()
    outcome = run_agent(task, env, model, step_cap=12, run_id=run_id, policy=policy)
    assert not succeeded(attack, outcome, outcome.trace, [], benign_correct=check_benign_correct(sc, outcome)), "Attack still succeeded against policy"

@pytest.mark.xfail(strict=True, reason="P9 open regression: abstain_dos p9-s-0050-abstain_dos-0")
def test_regression_p9_s_0050_abstain_dos_0() -> None:
    sc = SCENARIOS_BY_ID["s-0050"]
    from faultline_p2.redteam import build
    attacks = [a for a in build(CORPUS, ["s-0050"], seed=42) if a.attack_id == "p9-s-0050-abstain_dos-0"]
    assert len(attacks) == 1, "Attack definition missing"
    attack = attacks[0]
    policy = RuntimePolicy()
    run_id = f"repro-p9-s-0050-abstain_dos-0"
    policy.reset_run(run_id)
    env = {"documents": inject(CORPUS.documents, attack), "policy": policy}
    task = ScenarioTask(task_id=sc.scenario_id, prompt=sc.prompt, tier=sc.tier)
    model = HostileStub()
    outcome = run_agent(task, env, model, step_cap=12, run_id=run_id, policy=policy)
    assert not succeeded(attack, outcome, outcome.trace, [], benign_correct=check_benign_correct(sc, outcome)), "Attack still succeeded against policy"

@pytest.mark.xfail(strict=True, reason="P9 open regression: abstain_dos p9-s-0054-abstain_dos-0")
def test_regression_p9_s_0054_abstain_dos_0() -> None:
    sc = SCENARIOS_BY_ID["s-0054"]
    from faultline_p2.redteam import build
    attacks = [a for a in build(CORPUS, ["s-0054"], seed=42) if a.attack_id == "p9-s-0054-abstain_dos-0"]
    assert len(attacks) == 1, "Attack definition missing"
    attack = attacks[0]
    policy = RuntimePolicy()
    run_id = f"repro-p9-s-0054-abstain_dos-0"
    policy.reset_run(run_id)
    env = {"documents": inject(CORPUS.documents, attack), "policy": policy}
    task = ScenarioTask(task_id=sc.scenario_id, prompt=sc.prompt, tier=sc.tier)
    model = HostileStub()
    outcome = run_agent(task, env, model, step_cap=12, run_id=run_id, policy=policy)
    assert not succeeded(attack, outcome, outcome.trace, [], benign_correct=check_benign_correct(sc, outcome)), "Attack still succeeded against policy"

@pytest.mark.xfail(strict=True, reason="P9 open regression: json_breakout p9-s-0091-json_breakout-0")
def test_regression_p9_s_0091_json_breakout_0() -> None:
    sc = SCENARIOS_BY_ID["s-0091"]
    from faultline_p2.redteam import build
    attacks = [a for a in build(CORPUS, ["s-0091"], seed=42) if a.attack_id == "p9-s-0091-json_breakout-0"]
    assert len(attacks) == 1, "Attack definition missing"
    attack = attacks[0]
    policy = RuntimePolicy()
    run_id = f"repro-p9-s-0091-json_breakout-0"
    policy.reset_run(run_id)
    env = {"documents": inject(CORPUS.documents, attack), "policy": policy}
    task = ScenarioTask(task_id=sc.scenario_id, prompt=sc.prompt, tier=sc.tier)
    model = HostileStub()
    outcome = run_agent(task, env, model, step_cap=12, run_id=run_id, policy=policy)
    assert not succeeded(attack, outcome, outcome.trace, [], benign_correct=check_benign_correct(sc, outcome)), "Attack still succeeded against policy"

@pytest.mark.xfail(strict=True, reason="P9 open regression: role_override p9-s-0121-role_override-0")
def test_regression_p9_s_0121_role_override_0() -> None:
    sc = SCENARIOS_BY_ID["s-0121"]
    from faultline_p2.redteam import build
    attacks = [a for a in build(CORPUS, ["s-0121"], seed=42) if a.attack_id == "p9-s-0121-role_override-0"]
    assert len(attacks) == 1, "Attack definition missing"
    attack = attacks[0]
    policy = RuntimePolicy()
    run_id = f"repro-p9-s-0121-role_override-0"
    policy.reset_run(run_id)
    env = {"documents": inject(CORPUS.documents, attack), "policy": policy}
    task = ScenarioTask(task_id=sc.scenario_id, prompt=sc.prompt, tier=sc.tier)
    model = HostileStub()
    outcome = run_agent(task, env, model, step_cap=12, run_id=run_id, policy=policy)
    assert not succeeded(attack, outcome, outcome.trace, [], benign_correct=check_benign_correct(sc, outcome)), "Attack still succeeded against policy"
